version: '3.1'
services:
    express:
        container_name: cashapp-express
        restart: unless-stopped
        build: ./
        ports: 
            - "80:3000"
        links:
            - mongo
    mongo:
        image: mongo
        ports: 
            - "27017:27017"
        restart: unless-stopped
        volumes: 
            - ${dbdata}:/data/db

        

        
            