version: '3.1'
services:
    mongo:
        container_name: cashapp-mongo
        image: mongo
        ports: 
            - "27017:27017"
        restart: unless-stopped
        volumes: 
            - ${dbdata}:/data/db
            
    express:
        container_name: cashapp-express
        restart: unless-stopped
        build: ./
        ports: 
            - "3000:3000"
        links:
            - mongo
