version: '3.1'
services:
    mongo:
        container_name: cashapp-mongo
        image: mongo
        #ports: 
        #    - "27017:27017"
        restart: unless-stopped
        volumes:
            - ./data/db:/data/db
            
    express:
        container_name: cashapp-express
        restart: unless-stopped
        volumes:
            - ./data/db:/usr/src/app/public/images
        build: ./
        ports: 
            - "3000:3000"
        links:
            - mongo

    react:
        container_name: cashapp-react
        restart: unless-stopped
        build: ./frontend
        # volumes:
        #     - '.:/app'
        #     - '/app/node_modules'
        ports:
            - "9000:80"
        links:
            - express

